Lua-like stack-based architecture
ethanuppal/fernjit pull request #4
Opened 2024-09-03 20:20 UTC by Yey007

Switch to Lua-like architecture. There are some notes in TODOs about stuff that's bad about this PR so we can discuss. I'm not 100% sure how to best resolve these.

2024-09-04 07:13 UTC, ethanuppal commented on src/opcode.rs
> +pub const OP_CODE_BITS: usize = 8; // not using ::BITS here because types are just smallest thing that can fit,
I prefer code fencing `` all code even in non-doc comments

2024-09-04 07:16 UTC, ethanuppal commented on src/opcode.rs
> +/// Traits for types that can be encoded as part of an Op
```rs
/// Argument type for an operation. ???
trait EncodeIntoOp {}
```
btw, shouldn't this return `RawOp`?

2024-09-04 07:17 UTC, ethanuppal commented on src/opcode.rs
> -        decode!($encoded; $crate::arch::Word;
This is bad hygiene; in macros, we should always use full paths to types.

2024-09-04 07:19 UTC, ethanuppal commented on src/vm.rs
> +    fn move_ip(&mut self, new_ip: usize) -> Result<(), VMError> {
can we call this `jump` or smth

2024-09-04 07:19 UTC, ethanuppal commented on src/vm.rs
> +    fn move_ip(&mut self, new_ip: usize) -> Result<(), VMError> {
also should we make a `VMResult` type for convenience

2024-11-28 23:01 UTC, ethanuppal requested changes

2024-11-28 23:01 UTC, ethanuppal commented on src/coding.rs
> +pub trait Encodable<T> {
`EncodeInto`? I prefer more declarative names for traits. Do we want these functions in separate traits? If not, `EncodeInto` is a bad name. What about `TruncatedConvert`? That's too long I think.

2024-11-28 23:01 UTC, ethanuppal commented on src/coding.rs
>  /// Traits for types that can be encoded as part of an Op
[`Op`] so that it semantically links and looks like code.

2024-11-28 23:01 UTC, ethanuppal commented on src/arch.rs
> +use core::ops::Range;
nit: Add an empty line above

2024-11-28 23:01 UTC, ethanuppal commented on src/coding.rs
> +    fn decodes_signed_correctly() {
Does sign extension work properly?

2024-11-28 23:01 UTC, ethanuppal commented on src/opcode.rs
> -            return Some(encode!(Word;
Do you think we should make this `$crate::encode`?

2024-11-28 23:01 UTC, ethanuppal commented on src/vm.rs
> +                    .expect("illegal offset, too large for platform"); // explodes on microcontrollers
we're only worrying about x64

2024-11-28 23:01 UTC, ethanuppal commented on src/vm.rs
> +fn sign_extend_to<T: Unsigned + PrimInt>(
Do we really need the entire `num_traits` crate for this?

2024-11-28 23:01 UTC, ethanuppal commented on src/vm.rs
> +        for _ in 0..7 {
Can you factor the program out into a separate variable?

2024-11-28 23:02 UTC, ethanuppal commented
Do you sign extend decoded `ExtendedIntermediate`s?

2024-11-29 00:40 UTC, Yey007 commented on src/opcode.rs
> -            return Some(encode!(Word;
Probably

2024-11-29 19:05 UTC, ethanuppal commented
Can you run `git rebase --signoff HEAD~N` where `N` is the number of commits you've made up to and including the first unsigned commit?

2024-11-30 04:54 UTC, Yey007 commented on src/coding.rs
> +    fn decodes_signed_correctly() {
Probably not, but do we want to promise this as part of `decode!`? Currently nothing about `decode!` makes this promise--it is up to the user when implementing `CodeAsWord` to handle this if they feel like it. Our only promise is that we'll give you the `n` bits you asked for by writing `[..n..]` within the `Word` you get in `decode_from_word`.

2024-11-30 04:55 UTC, Yey007 commented on src/vm.rs
> +                    .expect("illegal offset, too large for platform"); // explodes on microcontrollers
do you think i should replace with `.unwrap()` then?

2024-11-30 05:03 UTC, Yey007 commented on src/vm.rs
> +fn sign_extend_to<T: Unsigned + PrimInt>(
Nope, fair point. We can probably get this done with a macro.

2024-11-30 05:14 UTC, Yey007 commented
Also, no, decoded `ExtendedImmediate`s are not sign extended right now by default. It is left up to the execution instruction, not the encoding, to do any sign extension if it wants to. I don't know if this is the right design or not, if you have ideas one way or another lmk.

2024-11-30 05:19 UTC, Yey007 commented
Rebased!

2024-11-30 05:39 UTC, ethanuppal commented on src/coding.rs
> +    fn decodes_signed_correctly() {
Good point

2024-11-30 05:39 UTC, ethanuppal commented on src/vm.rs
> +                    .expect("illegal offset, too large for platform"); // explodes on microcontrollers
Actually I realized I don't care

2024-11-30 05:40 UTC, ethanuppal approved these changes

2024-11-30 05:41 UTC, merged